service: image2pngascii
app: image2pngascii
org: merklebros
provider:
  name: aws
  runtime: python3.6
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  logs:
    restApi: true
package:
  include:
    - requirements.txt
    - generate_ascii_post.py
functions:
  generate_ascii_post:
    handler: generate_ascii_post.generate_ascii_post
    events:
      - http:
          path: /generate_ascii
          method: post
          contentHandling: CONVERT_TO_BINARY
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
